#!/usr/bin/env node
/**
 * Software Factory — code generator (Agent 2: "Claude writes the code").
 *
 * Reads the Claude-written spec, asks Claude for a concrete set of files, and
 * writes them into the repo (restricted to web/). Zero dependencies — uses Node's
 * native fetch (Node 18+). Keep in sync with factory/prompt_code.md.
 *
 * The GitHub Actions workflow (.github/workflows/factory.yml) runs this, then
 * validates that files changed, that web/ still installs, commits, and opens a PR.
 *
 * Environment:
 *   ANTHROPIC_API_KEY   required (unless DRY_RUN=1)
 *   SPEC                required — the implementation spec (Markdown)
 *   ISSUE_NUMBER        optional — for logging/commit context
 *   ISSUE_TITLE         optional
 *   ANTHROPIC_MODEL     optional — default "claude-sonnet-4-6"
 *   ALLOWED_PREFIX      optional — default "web/" (files must live here)
 *   MAX_FILES           optional — default 25
 *   DRY_RUN=1           optional — skip the API call, use a canned response
 *                       (lets you test file-writing without a key)
 *
 * Exit codes: 0 = files written, 1 = nothing written / hard error.
 */

import { writeFile, mkdir } from "node:fs/promises";
import path from "node:path";

const MODEL = process.env.ANTHROPIC_MODEL || "claude-sonnet-4-6";
const ALLOWED_PREFIX = (process.env.ALLOWED_PREFIX || "web/").replace(/\\/g, "/");
const MAX_FILES = parseInt(process.env.MAX_FILES || "25", 10);
const ISSUE_NUMBER = process.env.ISSUE_NUMBER || "0";
const ISSUE_TITLE = process.env.ISSUE_TITLE || "feature";
const SPEC = process.env.SPEC || "";
const ROOT = process.cwd();

const SYSTEM = `You are the Code Writer in an autonomous software factory.
You implement ONE GitHub issue's spec inside a small Node/Express app that lives in
the repo's "${ALLOWED_PREFIX}" folder.

Hard rules:
- Make the SMALLEST correct change that satisfies the spec.
- Touch ONLY files under "${ALLOWED_PREFIX}". Never write to worker/, render.yaml,
  scripts/, superplane/, .github/, or factory/.
- Keep the app runnable with "npm install && npm start" in ${ALLOWED_PREFIX}.
- Prefer plain Node/Express + vanilla front-end; do not add heavy dependencies.
- Output the COMPLETE final contents of every file you create or change (not a diff).

Output ONLY one JSON object, no code fences, no prose, exactly this shape:
{"files":[{"path":"${ALLOWED_PREFIX}server.js","content":"<full file contents>"}],"notes":"one short sentence"}`;

function buildUserPrompt() {
  return `Issue #${ISSUE_NUMBER}: ${ISSUE_TITLE}

Implementation spec to build:
---
${SPEC}
---

Return the JSON object now.`;
}

function cannedResponse() {
  // Used only when DRY_RUN=1, to exercise parsing + file writing offline.
  return JSON.stringify({
    files: [
      {
        path: `${ALLOWED_PREFIX}factory-demo.txt`,
        content: `Generated by the Software Factory dry-run for issue #${ISSUE_NUMBER}.\n`,
      },
    ],
    notes: "dry-run sample file",
  });
}

async function callClaude(system, user) {
  if (process.env.DRY_RUN === "1") return cannedResponse();

  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) throw new Error("ANTHROPIC_API_KEY is not set (and DRY_RUN!=1).");

  const res = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "x-api-key": apiKey,
      "anthropic-version": "2023-06-01",
      "content-type": "application/json",
    },
    body: JSON.stringify({
      model: MODEL,
      max_tokens: 8000,
      temperature: 0,
      system,
      messages: [{ role: "user", content: user }],
    }),
  });

  if (!res.ok) {
    const detail = await res.text().catch(() => "");
    throw new Error(`Anthropic API ${res.status}: ${detail.slice(0, 500)}`);
  }
  const data = await res.json();
  const text = (data.content || [])
    .map((c) => (typeof c.text === "string" ? c.text : ""))
    .join("")
    .trim();
  if (!text) throw new Error("Empty response from Claude.");
  return text;
}

// Pull the JSON object out of the model's reply, tolerating stray fences/prose.
function extractJson(text) {
  let t = text.trim();
  if (t.startsWith("```")) t = t.replace(/^```[a-zA-Z]*\s*/, "").replace(/```\s*$/, "");
  const start = t.indexOf("{");
  const end = t.lastIndexOf("}");
  if (start === -1 || end === -1 || end <= start) {
    throw new Error("No JSON object found in Claude's response.");
  }
  return JSON.parse(t.slice(start, end + 1));
}

// Resolve a model-supplied path safely: relative, no traversal, under ALLOWED_PREFIX.
function safeResolve(p) {
  const norm = String(p).replace(/\\/g, "/").replace(/^\.\//, "").replace(/^\/+/, "");
  if (!norm.startsWith(ALLOWED_PREFIX)) {
    throw new Error(`Refusing path outside ${ALLOWED_PREFIX}: ${p}`);
  }
  const abs = path.resolve(ROOT, norm);
  const base = path.resolve(ROOT, ALLOWED_PREFIX);
  if (abs !== base && !abs.startsWith(base + path.sep)) {
    throw new Error(`Path escapes ${ALLOWED_PREFIX}: ${p}`);
  }
  return { abs, rel: norm };
}

async function main() {
  if (!SPEC.trim()) {
    console.error("SPEC is empty — nothing to build. (Gate 1 should have stopped this.)");
    process.exit(1);
  }

  console.log(`Software Factory: generating code for issue #${ISSUE_NUMBER} with ${MODEL}…`);
  const raw = await callClaude(SYSTEM, buildUserPrompt());
  const obj = extractJson(raw);

  const files = Array.isArray(obj.files) ? obj.files : [];
  if (files.length === 0) throw new Error("Claude returned no files.");
  if (files.length > MAX_FILES) throw new Error(`Too many files (${files.length} > ${MAX_FILES}).`);

  let written = 0;
  for (const f of files) {
    if (!f || typeof f.path !== "string" || typeof f.content !== "string") {
      console.warn("Skipping malformed file entry:", JSON.stringify(f)?.slice(0, 120));
      continue;
    }
    const { abs, rel } = safeResolve(f.path);
    await mkdir(path.dirname(abs), { recursive: true });
    await writeFile(abs, f.content, "utf8");
    console.log(`  wrote ${rel} (${f.content.length} bytes)`);
    written++;
  }

  if (obj.notes) console.log(`notes: ${obj.notes}`);
  if (written === 0) {
    console.error("No valid files were written.");
    process.exit(1);
  }
  console.log(`Done — ${written} file(s) written under ${ALLOWED_PREFIX}.`);
}

main().catch((err) => {
  console.error("generate.mjs failed:", err.message || err);
  process.exit(1);
});
